# Generated by Django 5.0.6 on 2024-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='row_id')),
                ('category_id', models.CharField(max_length=50, verbose_name='Category id')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Name')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category Type',
                'db_table': 'tbl_category_type',
                'ordering': ['category_name'],
            },
        ),
    ]
